### PR TITLE
fix: add tabIndex support

### PR DESCRIPTION
**Pull request by wang-yikai**
I've created this pull request to fix https://github.com/ant-design/ant-design/issues/48059

### CODE REVIEW

**Comment by wang-yikai** [comment]
This is to fix https://github.com/ant-design/ant-design/issues/48059

**Comment by afc163** [comment]
Could you add a test case?

**Comment by wang-yikai** [comment]
@afc163 I've added some simple tests for `tabIndex`. Can you help merge the pull request?

**Comment by afc163** [comment]
Contained conflicting files

**Comment by wang-yikai** [comment]
@afc163 I fixed the conflicts. Let me know if you can merge this pull request, thanks!

**Comment by Chevindu** [comment]
Hi all, I'd like to know if there is more to be done regarding this PR. Happy to contribute in any way I can to get this merged.

**Comment by wang-yikai** [comment]
@Chevindu Can you resolve the conflicts (https://github.com/react-component/picker/pull/779/conflicts) and merge my pull request? The conflict is just the import order which should've been resolved by my latest push (https://github.com/react-component/picker/compare/477c6bf8899a308c1d5a1f464f465defc5dcfccb..cb7e3ed5383efe7a1f707d7e705b4982e298fe27).

**Comment by Chevindu** [comment]
@wang-yikai I don't have that access to either the main repo or your fork. Will you please be able to rebase/merge from the upstream master and add another commit? I think that should resolve all conflicts.

**Comment by wang-yikai** [comment]
@Chevindu I've just made a push in my fork. The conflicts should be resolved now. Let me know if you're able to merge, thank you!

**Comment by Chevindu** [comment]
@wang-yikai Thank you. But I do not have that privilege.

@afc163 Will you kindly be able look into this?

**Pull request merged**
