### PR TITLE
🐛 fix: disabledDate is not work when selecting time directly

### PR DESCRIPTION
**Pull request by Kermit-Xuan**
[#25746](https://github.com/ant-design/ant-design/issues/25746)

### CODE REVIEW

**Comment by Kermit-Xuan** [comment]
@zombieJ

**Comment by hoho2017** [comment]
it's still work when user choose this memont
image

**Comment by Kermit-Xuan** [comment]
I notice this problem, but it's different from the confirmation button.

Because the 'now' is dynamic, we don't know whether it's disabled when opening panel. It's only confirmed when the user clicks the `now` button.

Therefore, we can make the click have no effect when clicking the `now` button.

**Comment by hoho2017** [comment]
> I notice this problem, but it's different from the confirmation button.
> 
> Because the 'now' is dynamic, we don't know whether it's disabled when opening panel. It's only confirmed when the user clicks the `now` button.
> 
> Therefore, we can make the click have no effect when clicking the `now` button.

Can we check the input value when the choos time tab hid~~

**Comment by Kermit-Xuan** [comment]
> > I notice this problem, but it's different from the confirmation button.
> > Because the 'now' is dynamic, we don't know whether it's disabled when opening panel. It's only confirmed when the user clicks the `now` button.
> > Therefore, we can make the click have no effect when clicking the `now` button.
> 
> Can we check the input value when the choos time tab hid~~

We can don't submit it if the result of `disabledTime` is `true` when the user clicks `now` button

But we can't disable the `now` button when open panel.

**Comment by hoho2017** [comment]
> > > I notice this problem, but it's different from the confirmation button.
> > > Because the 'now' is dynamic, we don't know whether it's disabled when opening panel. It's only confirmed when the user clicks the `now` button.
> > > Therefore, we can make the click have no effect when clicking the `now` button.
> > 
> > 
> > Can we check the input value when the choos time tab hid~~
> 
> We can don't submit it if the result of `disabledTime` is `true` when the user clicks `now` button
> 
> But we can't disable the `now` button when open panel.

i know we can't submit it but if we remove the disabledTime value will be better^^

**Comment by zombieJ** [comment]
`+ rc-picker@1.13.1`

**Pull request merged**
