### PR TITLE
docs: Move to dumi

### PR DESCRIPTION
**Pull request by zombieJ**

### CODE REVIEW

**Comment by afc163** [comment]
拉个 project 看看还有哪几个没迁移完。

**Comment by zombieJ** [comment]
> 拉个 project 看看还有哪几个没迁移完。

@MadCcc  Pick this task.

ref: https://github.com/orgs/react-component/projects/1

**Comment by xrkffgg** [comment]
https://github.com/react-component/field-form/issues/238

**Comment by xrkffgg** [comment]
~~~  好久没搞了。。。。

**Pull request merged**
