### PR TITLE
fix: add comments and warnings for the deprecated property defaultPic…

### PR DESCRIPTION
**Pull request by zbw-zbw**
Add comments and warnings for the deprecated property defaultPickerValue

about:
[issues](https://github.com/ant-design/ant-design/issues/41974)
[ant-design-pr](https://github.com/ant-design/ant-design/pull/43781)

### CODE REVIEW

**Review by Wxh16144 — COMMENTED** [review]
可以参考 https://github.com/react-component/picker/commit/d6c0e61c1698627e65f6be552bf05b3f3db0df17#diff-aa79defbca4231fbbbc7a7fce45993745255dad38aeaf51d0c6c747fd89b759d 补充一个 测试用例,  3Q~

**Comment by zbw-zbw** [comment]
> 可以参考 [d6c0e61#diff-aa79defbca4231fbbbc7a7fce45993745255dad38aeaf51d0c6c747fd89b759d](https://github.com/react-component/picker/commit/d6c0e61c1698627e65f6be552bf05b3f3db0df17#diff-aa79defbca4231fbbbc7a7fce45993745255dad38aeaf51d0c6c747fd89b759d) 补充一个 测试用例, 3Q~

好的，我补充下

**Comment by zbw-zbw** [comment]
> 可以参考 [d6c0e61#diff-aa79defbca4231fbbbc7a7fce45993745255dad38aeaf51d0c6c747fd89b759d](https://github.com/react-component/picker/commit/d6c0e61c1698627e65f6be552bf05b3f3db0df17#diff-aa79defbca4231fbbbc7a7fce45993745255dad38aeaf51d0c6c747fd89b759d) 补充一个 测试用例, 3Q~

已补充哈～

**Comment by zbw-zbw** [comment]
> > 可以参考 [d6c0e61#diff-aa79defbca4231fbbbc7a7fce45993745255dad38aeaf51d0c6c747fd89b759d](https://github.com/react-component/picker/commit/d6c0e61c1698627e65f6be552bf05b3f3db0df17#diff-aa79defbca4231fbbbc7a7fce45993745255dad38aeaf51d0c6c747fd89b759d) 补充一个 测试用例, 3Q~
> 
> 已补充哈～

@Wxh16144 大佬 还有什么要调整的吗？

**Review by yoyo837 — APPROVED** [review]

**Review by Wxh16144 — APPROVED** [review]

**Comment by zbw-zbw** [comment]
@yoyo837 大佬你好 这个 pr 可以合并了吧？我看都 review 过了😊

**Comment by zbw-zbw** [comment]
哦对我 antd 那边还有一个相关的 issue 还没通过 得等那个一起
https://github.com/ant-design/ant-design/pull/43781

**Pull request merged**
