### PR TITLE
fix: add `autoComplete` support

### PR DESCRIPTION
**Pull request by harunurhan**
Ref: https://github.com/ant-design/ant-design/issues/22499

### CODE REVIEW

**Comment by rendongsc** [comment]
@afc163  老铁，12天过去了，这个还不能用？

**Comment by FabienDeborde** [comment]
@afc163 Can you please tell us when this is going to be merged in the main antd version?

**Comment by FabienDeborde** [comment]
@afc163
I am sorry but is there any news about when this is going to be merged?
It seems it should be only a bump in ant library package.json, is there any check to do before the merge occur? Not sure I can help, but I can do something to help speed the process please tell me.

**Comment by harunurhan** [comment]
@FabienDeborde 

If you're using `yarn` you can just use [resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to enforce different dependency of your dependency.

In that case I think below would work.

```
  "resolutions": {
    "antd/rc-picker": "1.4.15",
  }
```

**Comment by FabienDeborde** [comment]
@harunurhan 
Thanks for your answer! 
I had already tried this solution with no luck, but gave it another try this morning after deleting my yarn.lock file and it works!
By the way, the correct version is `"antd/rc-picker": "1.5.1"`

**Pull request merged**
