### PR TITLE
fix: should not trigger blur event while picker's input focused

### PR DESCRIPTION
**Pull request by kiner-tang**
- fix: https://github.com/ant-design/ant-design/issues/38350

### CODE REVIEW

**Comment by afc163** [comment]
图片

`npm run compile` is broken when publish it, could you check it?

**Comment by afc163** [comment]
https://github.com/react-component/picker/actions/runs/3400317986/jobs/5654679396

**Comment by kiner-tang** [comment]
> https://github.com/react-component/picker/actions/runs/3400317986/jobs/5654679396



> 图片
> 
> `npm run compile` is broken when publish it, could you check it?

ok

**Comment by kiner-tang** [comment]
> 图片
> 
> `npm run compile` is broken when publish it, could you check it?

This 'pr' will solve the compilation error problem

- https://github.com/react-component/picker/pull/514

**Pull request merged**
