### PR TITLE
fix: resolve deprecated warning display unexpected issue

### PR DESCRIPTION
**Pull request by kiner-tang**
- fix https://github.com/ant-design/ant-design/issues/41751

### CODE REVIEW

**Comment by afc163** [comment]
加个用例？

**Comment by kiner-tang** [comment]
> 加个用例？

好的

**Comment by kiner-tang** [comment]
> 加个用例？

done

**Comment by afc163** [comment]
antd 最好也升一下 rc-picker 并发个 patch https://github.com/react-component/picker/releases/tag/v3.5.2

**Pull request merged**
