### PR TITLE
fix: map to correct locales for date-fns

### PR DESCRIPTION
**Pull request by spawnia**
Resolves https://github.com/react-component/picker/issues/147

### CODE REVIEW

**Comment by Saarnaki** [comment]
Why has this not been merged? This change would solve the issue for several locales. Spawnia has done the tedious work of mapping the locales, why not reap the benefit already? Really need this for our product!

**Comment by tvojtech** [comment]
@MadCcc would it be possible to merge this PR?

**Comment by zombieJ** [comment]
Is that a more common way to auto generate locale? Seems this will has much maintain effort if enum all the locale.

**Comment by MadCcc** [comment]
```
const dealLocal = (str: string) => {
  const head = str.slice(0, str.indexOf('_'));
  return Locale.hasOwnProperty(head) ? head : str.replace(/_/g, '');
}
```

Maybe this way?

**Comment by spawnia** [comment]
I thought about a generalized solution, but in this case it is not worth it. Creating this pull request took me a few minutes of (admittedly tedious) work, but saved the time required to think through, test and future-proof another solution. The addition or removal of future locales should not happen often, and will be very easy to do and require little to no thought or testing.

**Comment by henrikskog** [comment]
Any updates on why this is not being merged? @MadCcc

**Comment by fasenderos** [comment]
Hello, 2 years later the #147 we are facing the same bug for the `it_IT`.

> ```ts
> const dealLocal = (str: string) => {
>   const head = str.slice(0, str.indexOf('_'));
>   return Locale.hasOwnProperty(head) ? head : str.replace(/_/g, '');
> }
> ```
> 
> Maybe this way?

The solution proposed by @MadCcc seems more general and would solve the issue for all locales. Really need this thanks

**Comment by lihue** [comment]
this works for me:

`
const dealLocal = (locale: string) => {
  const loc = locale.replace(/_/g, '');
  const head = locale.slice(0, locale.indexOf('_'));
  return Locale[loc] ? loc : head;
};
`

**Comment by spawnia** [comment]
> Rebase please.

Rebased and updated with the latest locales.

**Comment by zombieJ** [comment]
I've checked the locale file find that @MadCcc  maybe the better solution. Please help check on this: https://github.com/react-component/picker/pull/763

For example, manually map the `ar_EG` to `ar` is not correct for the `weekStartsOn`. The `arEG` is `0` but `ar` is `6`. It should always use the full path match and then fallback to the abbr version.

**Pull request closed without merging**
